basePath: /reticket/api/v1
definitions:
  controller.JSONResult:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  v1.reticketRecv:
    properties:
      ticket_outside_id:
        type: string
    required:
    - ticket_outside_id
    type: object
host: localhost:8082
info:
  contact:
    email: ly_yong@qq.com
    name: LiuYong
  description: 负责处理与支付和退款相关的业务
  title: 支付服务
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      description: 服务器执行退票请求
      parameters:
      - description: 用户ID
        in: query
        name: userID
        required: true
        type: string
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 需要接受的信息
        in: body
        name: wantPayR
        required: true
        schema:
          $ref: '#/definitions/v1.reticketRecv'
      produces:
      - application/json
      responses:
        "200":
          description: 返回成功
          schema:
            $ref: '#/definitions/controller.JSONResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: 告诉服务器执行退票请求
swagger: "2.0"
