// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "LiuYong",
            "email": "ly_yong@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "发送需要候补的信息给服务器, 服务器将执行候补功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "请求服务器执行候补功能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "需要接受的信息",
                        "name": "wantPayR",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.candidateRecv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.JSONResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.candidateSend"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.JSONResult"
                        }
                    }
                }
            }
        },
        "/cash": {
            "post": {
                "description": "发送需要候补的信息给服务器, 服务器将执行候补功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "请求服务器执行候补功能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "需要接受的信息",
                        "name": "wantPayR",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.cashRecv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/controller.JSONResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.JSONResult"
                        }
                    }
                }
            }
        },
        "/state": {
            "post": {
                "description": "发送需要候补的信息给服务器, 服务器将执行候补功能",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "请求服务器执行候补功能",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "需要接受的信息",
                        "name": "wantPayR",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.readRecv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.JSONResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.readSend"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.JSONResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.JSONResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.candidateRecv": {
            "type": "object",
            "required": [
                "date",
                "passengers",
                "time",
                "train_number"
            ],
            "properties": {
                "date": {
                    "description": "发车日期 yyyy-mm-dd",
                    "type": "string"
                },
                "passengers": {
                    "description": "乘客id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "time": {
                    "description": "发车时间 hh:mm",
                    "type": "string"
                },
                "train_number": {
                    "description": "车次",
                    "type": "string"
                }
            }
        },
        "v1.candidateSend": {
            "type": "object",
            "required": [
                "order_outside_id"
            ],
            "properties": {
                "order_outside_id": {
                    "description": "返回的订单编号",
                    "type": "string"
                }
            }
        },
        "v1.cashRecv": {
            "type": "object",
            "required": [
                "candidate_id"
            ],
            "properties": {
                "candidate_id": {
                    "type": "string"
                }
            }
        },
        "v1.readRecv": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "description": "候补id",
                    "type": "string"
                }
            }
        },
        "v1.readSend": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "type": "string"
                },
                "passengers": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "certificate_number": {
                                "description": "证件号",
                                "type": "string"
                            },
                            "name": {
                                "description": "乘客名",
                                "type": "string"
                            },
                            "type": {
                                "description": "乘客类型 0为普通乘客, 1为学生",
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8082",
	BasePath:    "/candidate/api/v1",
	Schemes:     []string{},
	Title:       "支付服务",
	Description: "负责处理与支付和退款相关的业务",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
