version: '3.5'
services:
  pay-server:
    build:
      context: ./server/pay
    ports:
      - "8082:8082"
    network_mode: "host"
  reticket-server:
    build:
      context: ./server/reticket
    ports:
      - "8092:8092"
    network_mode: "host"
  candidate-server:
    build:
      context: ./server/candidate
    ports:
      - "8102:8102"
    network_mode: "host"
  mysql:
    ports:
      - "3310:3306"
    volumes:
      - "~/data/docker-mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=12306A.12306A"
    image:
      mysql
  redis:
    ports:
      - "6379:6379"
    image:
      redis
  zipkin:
    ports:
      - "9410:9410/tcp"
      - "9411:9411/tcp"
    image:
      openzipkin/zipkin
    # 将nginx独立, 在服务器上创建
#  nginx:
#    image:
#      lyyong/12306a_nginx:v0.1.1
#    ports:
#    - "80:80"
#  fabio:
#    build:
#      context: ./docker/fabio
#      labels:
#        - "latest"
#    ports:
#    - "9999:9999"
#    - "9998:9998"
  consul:
    build:
      context: ./docker/consul
      labels:
        - "latest"
    ports:
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8500:8500/tcp"
      - "8600:8600/tcp"
      - "8600:8600/udp"