version: '3.5'
services:
  user-server:
    build:
      context: .
      dockerfile: ./server/user/Dockerfile
    ports:
      - "8222:8222/tcp"
  pay-server:
    build:
      context: ./server/pay
    ports:
      - "8082:8082"
  candidate-server:
    build:
      context: ./server/candidate
    ports:
      - "8102:8102"
  mysql:
    ports:
      - "3310:3306"
    volumes:
      - "~/data/docker-mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=12306A.12306A"
    image:
      mysql
  main-redis:
    ports:
      - "6379:6379"
    image:
      redis
  slave-redis:
    build:
      context: ./docker/redis/slave_tp
    ports:
      - "6380:6380"
  zipkin:
    ports:
      - "9410:9410/tcp"
      - "9411:9411/tcp"
    image:
      openzipkin/zipkin
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
  consul:
    build:
      context: ./docker/consul
      labels:
        - "latest"
    ports:
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8500:8500/tcp"
      - "8600:8600/tcp"
      - "8600:8600/udp"
  kafka-manager:
    image:
      kafkamanager/kafka-manager
    ports:
      - "9111:9000"
    environment:
      ZK_HOSTS: zoo:2181
  kafka:
    image:
      wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "PayOK:1:1"
  zoo:
    image:
      zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
